import PDFDocument from "pdfkit";

/**
 * Build a self-assessment PDF from server-validated fields (PSZL-015).
 * @param {object} report
 * @returns {Promise<Buffer>}
 */
export function buildSelfAssessmentReportPdf(report) {
    const {
        companyName,
        auditorName,
        auditCompany,
        standard,
        score,
        date,
        questions,
    } = report;

    return new Promise((resolve, reject) => {
        const doc = new PDFDocument({ margin: 48, size: "A4" });
        const chunks = [];
        doc.on("data", (chunk) => chunks.push(chunk));
        doc.on("end", () => resolve(Buffer.concat(chunks)));
        doc.on("error", reject);

        const total = questions?.length || 0;
        const yesCount = questions?.filter((q) => q.answer === "yes").length || 0;
        const noCount = questions?.filter((q) => q.answer === "no").length || 0;
        const percentage = total > 0 ? Math.round((yesCount / total) * 100) : 0;
        const stage = score >= 38 ? "Mature Stage" : score >= 25 ? "Moderate Stage" : "Early Stage";

        doc.fontSize(20).fillColor("#213847").text("Self Assessment Report", { align: "center" });
        doc.moveDown(0.5);
        doc.fontSize(12).fillColor("#475569").text(String(standard || ""), { align: "center" });
        doc.moveDown(1.5);

        doc.fontSize(11).fillColor("#0f172a");
        doc.text(`Company: ${companyName || "-"}`);
        if (auditCompany) doc.text(`Company being audited: ${auditCompany}`);
        doc.text(`Auditor: ${auditorName || "-"}`);
        if (date) {
            doc.text(
                `Date: ${new Date(date).toLocaleDateString("en-GB", {
                    day: "numeric",
                    month: "long",
                    year: "numeric",
                })}`,
            );
        }
        doc.moveDown(1);

        doc.fontSize(14).fillColor("#0f172a").text(`Overall score: ${score} / 50 (${percentage}%)`);
        doc.fontSize(11).text(`Maturity stage: ${stage}`);
        doc.text(`Responses: ${yesCount} Yes · ${noCount} No · ${total} Total`);
        doc.moveDown(1);

        doc.fontSize(13).text("Score by clause", { underline: true });
        doc.moveDown(0.5);

        const clauseGroups = {};
        for (const q of questions || []) {
            const clauseKey = String(q.clause || "General").slice(0, 200);
            if (!clauseGroups[clauseKey]) clauseGroups[clauseKey] = { yes: 0, total: 0 };
            clauseGroups[clauseKey].total += 1;
            if (q.answer === "yes") clauseGroups[clauseKey].yes += 1;
        }

        doc.fontSize(10).fillColor("#334155");
        for (const [clause, data] of Object.entries(clauseGroups)) {
            const pct = data.total > 0 ? Math.round((data.yes / data.total) * 100) : 0;
            doc.text(`${clause}: ${data.yes}/${data.total} (${pct}%)`);
        }

        doc.moveDown(2);
        doc.fontSize(9).fillColor("#64748b").text(
            "Generated by iAudit Global. This PDF was produced on the server from your assessment submission.",
            { align: "center" },
        );

        doc.end();
    });
}
