export const NOTIFICATION_TYPES = Object.freeze({
    NC_ASSIGNED: 'NC_ASSIGNED',
    NC_RESPONSE_SUBMITTED: 'NC_RESPONSE_SUBMITTED',
    NC_CHANGES_REQUESTED: 'NC_CHANGES_REQUESTED',
    NC_CLOSED: 'NC_CLOSED',
});

export const NOTIFICATION_TYPE_VALUES = Object.freeze(Object.values(NOTIFICATION_TYPES));
